### ISSUE TITLE
Error setting up the site

### ISSUE THREAD

**Issue by guribe94** [llazzaro/django-scheduler-sample#3]
Hi I am trying to set up the sample site by following the instructions given. I created a virtualenv and installed all the requirements in requirements.txt but when I try to run `./manage.py syncdb` I am given this error. 

`Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/parallels/.virtualenvs/scheduler-sample/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/parallels/.virtualenvs/scheduler-sample/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/parallels/.virtualenvs/scheduler-sample/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/parallels/.virtualenvs/scheduler-sample/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/parallels/.virtualenvs/scheduler-sample/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named djangobower`

Is there something else I should be doing before running `syncdb`?

**Comment by guribe94** [comment]
Also wanted to note that I tried with both python3 and python2. Got the same error

**Comment by llazzaro** [comment]
did you install dev version of scheduler ? or did you use pip install django-scheduler?

**Comment by llazzaro** [comment]
done please update the scheduler sample repo with git pull, then pip install -r requirements.txt.

please follow the instructions here:
https://github.com/llazzaro/django-scheduler/blob/master/README.md

you need to have npm in order to use the newer version of scheduler.
