### ISSUE TITLE
Cannot find /components directory

### ISSUE THREAD

**Issue by rowanv** [llazzaro/django-scheduler-sample#5]
Hi,

When I attempt to run the scheduling project, I get the following error:

```
Traceback (most recent call last):
  File "/Users/me/virtualenvs/r/lib/python2.7/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/Users/me/virtualenvs/r/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 94, in process_response
    new_response = panel.process_response(request, response)
  File "/Users/me/virtualenvs/r/lib/python2.7/site-packages/debug_toolbar/panels/staticfiles.py", line 126, in process_response
    'staticfiles_finders': self.get_staticfiles_finders(),
  File "/Users/me/virtualenvs/r/lib/python2.7/site-packages/debug_toolbar/panels/staticfiles.py", line 137, in get_staticfiles_finders
    for path, finder_storage in finder.list([]):
  File "/Users/me/virtualenvs/r/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 112, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/Users/me/virtualenvs/r/lib/python2.7/site-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
    directories, files = storage.listdir(location)
    File "/Users/me/virtualenvs/r/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in listdir
```

No such file or directory:
'/Users/me/workspace/django-scheduler-sample/components'

Do you know why it is looking for that specific folder, which does not appear to be included in the repository? Thanks,

**Comment by llazzaro** [comment]
I think you are missing the step : ./manage.py bower install

please read this on how to install django-scheduler https://github.com/llazzaro/django-scheduler/blob/develop/README.md

I will try to make this more automatic.
To get js libs we are using bower now
